import Head from 'next/head'
import Header from '../components/header'
import Nav from '../components/nav'
import Results from '../components/results_c'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* nav */}
      <Nav />
      {/* results */}
      <Results /> 


    </div>
  )
}
export async function getServerSideProps(context) {

}